print("Ronit Satish Mehta SAP ID:- 60009230207")
l = int(input("enter the length of the triangle"))
b = int(input("enter the breadth of the triangle"))
print("the area of the triangle:",1/2 * (l *b))
print("the area of  the rectangle:", l * b)
print("the area of the sqaure:",l*l)
